version: '3.7'
x-common-variables: &common-variables
  NODE_ENV: local
  DB_MAIN_HOST: mongo
  DB_MAIN_USER: admin
  DB_MAIN_PASS: himeji
  DB_MAIN_NAME: eleva
  TOKEN_SECRET: elevasystems

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf 
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ~/./html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=elevasystems.com.ar,www.elevasystems.com.ar
      - LETSENCRYPT_HOST=elevasystems.com.ar,www.elevasystems.com.ar
      - LETSENCRYPT_EMAIL=cingolanifede@elevasystems.com.ar
    depends_on:
      - nginx-proxy
      - letsencrypt

  local:
    build:
      context: .
      target: builder
    image: elevasystems-backend
    volumes:
      - ./:/app/
    container_name: elevasystems-backend_local
    environment: *common-variables
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 25:25
    tty: true
    restart: unless-stopped
    command: /bin/sh -c "npm install && npm run start-dev"

  mongo:
    image: mongo
    container_name: elevasystems-database-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - database:/data/db


volumes: 
  certs:
  html:
  vhostd:
  database: